name: Validate Terraform Configuration

on:
  push:
    branches:
      - main 

jobs:
  validate-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: '1.5.4'
    - name: Run Terraform Tests with LocalStack
      uses: dhollerbach/actions.terraform-tests-with-localstack@v1
      with:
        run-formatter: true
        run-linter: true
        run-security-scanner: true
        run-apply: true
        terraform-version: 1.11.0

    - name: Validate Terraform configuration
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform validate
