name: Validate
on:
  push:
    branches:
      -main
jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate Terraform module
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: terraform init
        run: terraform init
      - name: terraform validate
        run: terraform validate
