name: Validate Terraform Configuration with LocalStack

on:
  push:
    branches:
      - main

jobs:
  validate-terraform:
    runs-on: ubuntu-latest

    services:
      localstack:
        image: localstack/localstack
        env:
          SERVICES: s3,sqs,sns
          DEFAULT_REGION: us-east-1
          PORT_WEB_UI: 8080
        ports:
          - 4566:4566
          - 8080:8080

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: '1.0.0'
    - name: Configure AWS credentials for LocalStack
      run: |
        mkdir -p ~/.aws  # Ensure the directory exists
        echo "[default]" >> ~/.aws/credentials
        echo "aws_access_key_id=test" >> ~/.aws/credentials
        echo "aws_secret_access_key=test" >> ~/.aws/credentials
        echo "[default]" >> ~/.aws/config
        echo "region=us-east-1" >> ~/.aws/config
        echo "output=json" >> ~/.aws/config   

    - name: Configure AWS credentials for LocalStack
      run: |
        echo "[default]" >> ~/.aws/credentials
        echo "aws_access_key_id=test" >> ~/.aws/credentials
        echo "aws_secret_access_key=test" >> ~/.aws/credentials
        echo "[default]" >> ~/.aws/config
        echo "region=us-east-1" >> ~/.aws/config
        echo "output=json" >> ~/.aws/config

    - name: Validate Terraform configuration
      run: |
        terraform init
        terraform validate
